[[redirects]]
  from = "/request"
  to = "https://ade-uga-ro-vs.grenet.fr/jsp/webapi"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
