[[redirects]]
  from = "/request"
  to = "https://ade-uga-ro-vs.grenet.fr/jsp/webapi"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[headers]]
  for = "/request"
  [headers.values]
    access-control-allow-origin = "no-cors"