[[redirects]]
  from = "/request"
  to = "https://ade-uga-ro-vs.grenet.fr/jsp/webapi"
  status = 200
  force = true
  headers = {
    Access-Control-Allow-Origin = "*"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404