[[redirects]]
  from = "/request"
  to = "https://ade-uga-ro-vs.grenet.fr/jsp/webapi"
  status = 200
  force = true

[[redirects]]
  from = "/localRequest"
  to = "/.netlify/functions/request"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
